{{ if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "partner-bank-interface.name" . }}
  labels:
    {{- include "partner-bank-interface.labels" . | nindent 4 }}
    {{- if .Values.service.labels }}
    {{ toYaml .Values.service.labels | indent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
  {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{- if contains "NodePort" .Values.service.type }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      targetPort: http
      protocol: TCP
      name: http
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{ toYaml .Values.service.loadBalancerSourceRanges | indent 4 }}
  {{- end -}}
  {{- if .Values.service.externalIPs }}
  externalIPs:
  {{ toYaml .Values.service.externalIPs | indent 4 }}
  {{- end }}
  selector:
    {{- include "partner-bank-interface.selectorLabels" . | nindent 4 }}
{{ end }}