apiVersion: v2
name: api-gateway
description: Helm chart for API gateway application
type: application
version: 2.29.0
appVersion: 2.29.0
annotations:
  helm.sh/images: |
    - name: api-gateway-ms
      image: docker.io/hrvestigo/api-gateway-ms:2.29.0
